#!/usr/bin/env bash
# Borra docs redundantes del root de super-app.
# Uso: bash scripts/cleanup-docs.sh /ruta/a/super-app
set -e
DIR="${1:-.}"
cd "$DIR"

FILES=(
  STATUS.txt DIAGNOSTICO.txt LEE_ESTO.txt ESTADO_FINAL.md PROJECT_COMPLETE.txt
  LISTO_PARA_PRODUCCION.txt VERIFICACION_FINAL.txt RESUMEN_DETALLADO.txt
  README_INICIO.txt QUICK_START.txt FILE_MANIFEST.txt PENDING_FEATURES.txt
  ESTADO_RESUELTO.txt PHASE_1_IMPLEMENTATION.md PHASE_1_STATUS.md
  FASE_1_COMPLETA.md FASE_2_IMPLEMENTATION_PLAN.md
  BUILD_IN_PROGRESS_TRACKER.md EPIC_SUMMARY.md
  00_PROJECT_COMPLETION_SUMMARY.md IMPORTANT_FEATURES_COMPLETE.md
  INTEGRATION_COMPLETE.md STATUS_COMPLETO_100_.md COMPLETE_SUMMARY.md
  IMPLEMENTATION_SUMMARY.md FINAL_VERIFICATION_REPORT.md VERIFICATION_REPORT.md
  PROJECT_DIAGNOSTICS.md MASTER_PLAN_POST_BUILD.md POST_BUILD_TASKS.md
)

for f in "${FILES[@]}"; do
  if [ -f "$f" ]; then
    rm -v "$f"
  fi
done

echo "Listo. Conserva: README.md SETUP.md DEPLOYMENT.md FEATURES.md .env.example"
